version: '3.4'

services:
  eventbus:
    image: rabbitmq:3-management
    profiles: [ all, eventbus, backend ]
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: p@ssw0rd
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 60s

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    profiles: [ all, backend ]
    depends_on:
     - dashboardservice
     - tileservice
    ports:
      - "5500:80/tcp"

  dashboardservice:
    image: dashboardservice:latest
    profiles: [ all, backend ]
    build:
      context: .
      dockerfile: Workshop.DashbpoardService/Dockerfile
      args:
        CONFIGURATION: Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - eventbus
  
  tileservice:
    image: tileservice:latest
    profiles: [ all, backend ]
    build:
      context: .
      dockerfile: Workshop.TileService/Dockerfile
      args:
        CONFIGURATION: Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - eventbus
 
  uiinfoservice:
    image: uiinfoservice:latest
    profiles: [ all, backend ]
    build:
      context: .
      dockerfile: Workshop.UiInfoService/Dockerfile
      args:
        CONFIGURATION: Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - eventbus
  